### ISSUE TITLE
Improve release page

### ISSUE THREAD

**Issue by locks** [ember-learn/handbook#41]
A new section was added to the release page, but it is not listed in the bullet point list at the top.

## Tasks
- [x] Add Wikipedia entry to the bullet list
- [x] Make bullet point list numbered to properly communicate ordering
- Bonus
  - [x] make bullet point list link to the various headers
  - [ ] add numbering to headers themselves
